urls:
  - url: https://raw.githubusercontent.com/github/rest-api-description/refs/heads/main/descriptions/api.github.com/api.github.com.json
    name: Example API 1
  - url: https://statistikdatabasen.scb.se/api/v2/swagger/v2/swagger.json
    name: Example API 2